### PR TITLE
Add configurable query timeout

### PR DESCRIPTION
**Pull request by ItsHarry**
If no value is set in the config, 0 is used which means no timeout (current behavior)

### CODE REVIEW

**Comment by Ichbinjoe** [comment]
Thanks, enjoy the T-Shirt :P

**Comment by ItsHarry** [comment]
t-shirt? o-o

**Comment by Ichbinjoe** [comment]
https://hacktoberfest.digitalocean.com/

Hahaha I figured you were doing this for the T-Shirt. Knowing you weren't actually makes me appreciate the PRs more. Thanks for the contributions!

**Comment by ItsHarry** [comment]
oh haha, didn't know

**Pull request merged**
