### PR TITLE
Added andOTP and FreeOtp to the list of 2FA applications.

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by ccuser44** [comment]
Not sure if I should add Aegis Auhthenticator.

**Review by CyberFlameGO — CHANGES_REQUESTED** [review]
I don’t believe this is necessary; people probably get the gist of this project supporting OTP

**Comment by aaomidi** [comment]
Agree with @CyberFlameGO

**Comment by ccuser44** [comment]
Then why were there added a list of OTPs anyway? Previously new OTPs were added to the list and that was fine.
#4 and #44

**Comment by CyberFlameGO** [comment]
Probably as examples of Windows Phone-compatible authentication apps. If people want an OTP app they can probably find one themselves 🤷‍♂️

**Pull request closed without merging**
